version: "3"
services:
  mqtt_broker:
    image: eclipse-mosquitto
    container_name: mqtt_broker
    stdin_open: true
    tty: true
    ports:
      - "1883:1883"
    networks:
      - local
    volumes:
      - ./mosquitto:/mosquitto
      

networks:
  local:
    driver: bridge
