name: Execute stale labeler
on:
  workflow_dispatch:
  schedule:
    - cron: "35 6 * * *"

permissions:
  contents: read
  actions: write
  issues: write
  pull-requests: write

jobs:
  labels:
    uses: equinor/armada/.github/workflows/mark_issues_and_prs_as_stale.yml@main
    secrets:
      STALE_ISSUE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
