name: Migration checks

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  migration_checks:
    uses: equinor/armada/.github/workflows/migration_checks.yml@main
    with:
      database_paths: "src/isar/services/service_connections/persistent_memory.py"
      migrations_paths: "alembic/versions/**"
