name: Notify migrations on PR

on:
  workflow_run:
    workflows: [Verify migrations]
    types: [completed]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  notify_migrations_on_pr:
    if: github.event.workflow_run.conclusion == 'success'
    uses: equinor/armada/.github/workflows/notify_migrations_on_pr.yml@main
    with:
      stage_one_workflow_run_id: ${{ github.event.workflow_run.id }}
      migration_docs_url: https://github.com/equinor/isar/tree/main/alembic/README.md
